export enum EnumHttpStatusCodes {
  OK = 200,
  CREATED = 201,
  ACCEPTED = 202,
  NO_CONTENT = 204,
  BAD_REQUEST = 400,
  UNAUTHORIZED = 401,
  FORBIDDEN = 403,
  NOT_FOUND = 404,
  INTERNAL_SERVER_ERROR = 500,
}

export enum EnumAPIResponseStatusType {
  SUCCESS = 'success',
  ERROR = 'error',
}


export enum EnumUnitOfMeasure {
  ACRE = 'acre',
  BAG = 'bag',
  BARREL_UK_PETROLEUM = 'barrel (uk petroleum)',
  BARREL_US = 'barrel (us)',
  BOTTLE = 'bottle',
  BOX = 'box',
  BRITISH_THERMAL_UNIT_MEAN = 'british thermal unit (mean)',
  BUNDLE = 'bundle',
  CALORIE_MEAN = 'calorie (mean)',
  CARTON = 'carton',
  CASE = 'case',
  CENTILITRE = 'centilitre',
  CENTIMETRE = 'centimetre',
  CRATE = 'crate',
  CUBIC_FOOT = 'cubic foot',
  CUBIC_INCH = 'cubic inch',
  CUBIC_METRE = 'cubic metre',
  CUBIC_MILLIMETRE = 'cubic millimetre',
  CUBIC_YARD = 'cubic yard',
  CYLINDER = 'cylinder',
  DAY = 'day',
  DECALITRE = 'decalitre',
  DECAMETRE = 'decametre',
  DECIMETRE = 'decimetre',
  DECITONNE = 'decitonne',
  DRUM = 'drum',
  EACH = 'each',
  FLUID_OUNCE_UK = 'fluid ounce (uk)',
  FLUID_OUNCE_US = 'fluid ounce (us)',
  FOOT = 'foot',
  GALLON_UK = 'gallon (uk)',
  GALLON_US = 'gallon (us)',
  GIGAJOULE = 'gigajoule',
  GIGAWATT_HOUR = 'gigawatt hour',
  GRAIN = 'grain',
  GRAM = 'gram',
  HECTARE = 'hectare',
  HECTOMETRE = 'hectometre',
  HOUR = 'hour',
  INCH = 'inch',
  JOULE = 'joule',
  KILOCALORIE_MEAN = 'kilocalorie (mean)',
  KILOGRAM = 'kilogram',
  KILOJOULE = 'kilojoule',
  KILOLITRE = 'kilolitre',
  KILOMETRE = 'kilometre',
  KILOTONNE = 'kilotonne',
  KILOWATT_HOUR = 'kilowatt hour',
  LITRE = 'litre',
  LITRE_PER_DAY = 'litre per day',
  LOT = 'lot',
  MANDAYS = 'mandays',
  MEGAGRAM = 'megagram',
  MEGAJOULE = 'megajoule',
  MEGALITRE = 'megalitre',
  MEGAWATT_HOUR = 'megawatt hour (1000 kw.h)',
  METRE = 'metre',
  MILE_STATUTE = 'mile (statute mile)',
  MILLIGRAM = 'milligram',
  MILLIMETRE = 'millimetre',
  MINUTE = 'minute [unit of time]',
  MONTH = 'month',
  NAUTICAL_MILE = 'nautical mile',
  OUNCE = 'ounce',
  PACKET = 'packet',
  PETAJOULE = 'petajoule',
  PIECE = 'piece',
  PIECES = 'pieces',
  POUND = 'pound',
  SECOND = 'second [unit of time]',
  SQ_CENTIMETRE = 'sq. centimetre',
  SQUARE_FOOT = 'square foot',
  SQUARE_INCH = 'square inch',
  SQUARE_KILOMETRE = 'square kilometre',
  SQUARE_METRE = 'square metre',
  SQUARE_YARD = 'square yard',
  STANDARD_CUBIC_FOOT = 'standard cubic foot',
  TERAWATT_HOUR = 'terawatt hour',
  TONNE_METRIC = 'tonne (metric ton)',
  TROY_OUNCE = 'troy ounce',
  UNIT = 'unit',
  WATT_HOUR = 'watt hour',
  WEEK = 'week',
  YARD = 'yard',
  YEAR = 'year',
}



export enum EnumIdentificationType {
  COMMERCIAL_REGISTRATION_NUMBER = 'commercial_registration_number',
  MOMRA_LICENSE = 'momra_license',
  MLSD_LICENSE = 'mlsd_license',
  SAGIA_LICENSE = 'sagia_license',
  MINISTRY_OF_JUSTICE_LICENSE = 'ministry_of_justice_license',
  OTHER_ID = 'other_id',
}


export enum EnumCustomerIdentificationType{
    NATIONAL_ID = 'national_id',
    TAX_IDENTIFICATION_NO = 'tax_identification_no',
    IQAMA_NUMBER = 'iqama_number',
    PASSPORT_ID = 'passport_id',
    SEVEN_HUNDRED_NUMBER = '700_number',
    COMMERCIAL_REGISTRATION_NUMBER = 'commercial_registration_number',
    MOMRA_LICENSE = 'momra_license',
    MLSD_LICENSE = 'mlsd_license',
    SAGIA_LICENSE = 'sagia_license',
    GCC_ID = 'gcc_id',
    MINISTRY_OF_JUSTICE_LICENSE = 'ministry_of_justice_license',
    OTHER_ID = 'other_id',
    COMPANY_REGISTRATION = 'company_registration'
}


export enum EnumIncoTerms {
  EXW = 'exw',
  FCA = 'fca',
  FAS = 'fas',
  FOB = 'fob',
  CPT = 'cpt',
  CFR = 'cfr',
  CIF = 'cif',
  CIP = 'cip',
  DPU = 'dpu',
  DAP = 'dap',
  DDP = 'ddp',
  NA  = 'na',
}



